<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <JellyfinVersion>12.0.0</JellyfinVersion>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Version>0.2.0.1</Version>
        <RootNamespace>Jellyfin.Plugin.SleekFin</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Jellyfin.Common" Version="$(JellyfinVersion)">
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Jellyfin.Model" Version="$(JellyfinVersion)">
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Jellyfin.Controller" Version="$(JellyfinVersion)">
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4">
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Configuration\config.html" />
        <EmbeddedResource Include="Inject\Theme\sleekfin-theme.css" />
        <EmbeddedResource Include="Inject\Theme\sleekfin-theme.js" />
        <EmbeddedResource Include="Inject\Components\sleekfin-icons.js" />
        <EmbeddedResource Include="Inject\Components\sleekfin-components.css" />
        <EmbeddedResource Include="Inject\Components\sleekfin-components.js" />
        <EmbeddedResource Include="Inject\Header\sleekfin-header.css" />
        <EmbeddedResource Include="Inject\Header\sleekfin-header.js" />
        <EmbeddedResource Include="Inject\Hero\sleekfin-hero.css" />
        <EmbeddedResource Include="Inject\Hero\sleekfin-hero.js" />
        <EmbeddedResource Include="Inject\Media\sleekfin-media.css" />
        <EmbeddedResource Include="Inject\Media\sleekfin-media.js" />
        <EmbeddedResource Include="Inject\Details\sleekfin-details.css" />
        <EmbeddedResource Include="Inject\Details\sleekfin-details.js" />
        <EmbeddedResource Include="Inject\Fonts\*.woff2" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\meta.json" Link="meta.json" CopyToOutputDirectory="Always" />
        <None Include="..\..\thumb.png" Link="thumb.png" CopyToOutputDirectory="Always" />
    </ItemGroup>

</Project>
